apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-server-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: INFRA_REPO_URL_PLACEHOLDER
               sed -i 's|repoURL: INFRA_REPO_URL_PLACEHOLDER
             done
    targetRevision: main
    path: helm/petclinic-service
    helm:
      releaseName: config-server
      valueFiles:
        - ../../helm-values/config-server.yaml
        - ../../helm-values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
