apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vets-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: INFRA_REPO_URL_PLACEHOLDER
    targetRevision: main
    path: helm/petclinic-service
    helm:
      releaseName: vets-service
      valueFiles:
        - ../../helm-values/vets-service.yaml
        - ../../helm-values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
