apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-email-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: alertmanager-email-secret
    creationPolicy: Owner
  data:
    - secretKey: email
      remoteRef:
        key: petclinic/dev/alertmanager-email
        property: email
    - secretKey: app_password
      remoteRef:
        key: petclinic/dev/alertmanager-email
        property: app_password
